### ISSUE TITLE
Error Setup and Run

### ISSUE THREAD

**Issue by m1ndcr4ck** [Raz0r/aemscan#9]
Hi there,

First at all thanks for the great job on this tool.

I just trying to install on Kali 2021.2  with the following command "python setup.py install" but I am getting the following error 

```
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
```
Then I tried with python3 instead of python and it looks that installed successfully, however when I tried to run I got the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/aemscan", line 33, in <module>
    sys.exit(load_entry_point('aemscan==1.0', 'console_scripts', 'aemscan')())
  File "/usr/local/bin/aemscan", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/aemscan-1.0-py3.9.egg/aemscan/__init__.py", line 7, in <module>
    from .types import URL
  File "/usr/local/lib/python3.9/dist-packages/aemscan-1.0-py3.9.egg/aemscan/types.py", line 4, in <module>
    from urlparse import urlparse
ModuleNotFoundError: No module named 'urlparse'
```

Cheers!

**Comment by Raz0r** [comment]
Hey, fixed this in #10
